runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -b :$PORT wsgi:app

runtime_config:
    python_version: 3

handlers:
    - url: /
      script: wsgi.app
    - url: /static
      static_dir: /

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 2
