name: Build and Deploy
runs-on: self-hosted

on:
  push:
    branches: master

env:
  APPNAME: arturonet
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push to docker
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          arturoguerra/${{ env.APPNAME }}:latest
          arturoguerra/${{ env.APPNAME }}:${{ github.sha }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Helm Repo
      uses: actions/checkout@v2
      with:
        repository: arturoguerra/arturonet-charts
        token: ${{ secrets.REPO_ACCESS }}
    - name: Installs yq
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
    - name: Update the Helm Chart values.yaml
      run: |
        yq w -i values.yaml website.image.tag ${{ github.sha }}
    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Updating Image Tag: ${{ github.sha }}"
        git push origin master
